apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    targetPort: {{ .Values.service.port }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
